<?php

namespace Tests\Magium\Magento2\Checkout;

use Magium\Magento\AbstractMagentoTestCase;
use Magium\Magento\Actions\Admin\Configuration\Enabler;
use Magium\Magento\Actions\Admin\Login\Login;
use Magium\Magento\Actions\Cart\AddItemToCart;
use Magium\Magento\Actions\Checkout\GuestCheckout;
use Magium\Magento2\ConfigurationSwitcher;

class SavedCCPaymentTest extends AbstractMagentoTestCase
{

    protected function setUp()
    {
        parent::setUp();
        (new ConfigurationSwitcher($this))->configure();
    }

    public function testSavedCC()
    {
        $this->getAction(Login::ACTION)->login();
        $this->getAction(Enabler::ACTION)->enable('Payment Methods/Saved CC');

        $this->commandOpen($this->getTheme()->getBaseUrl());
        $this->getAction(AddItemToCart::ACTION)->addSimpleProductToCartFromCategoryPage();
        $this->setPaymentMethod('SavedCC');
        $this->getAction(GuestCheckout::ACTION)->execute();
    }

    protected function tearDown()
    {
        $this->getAction(Login::ACTION)->login();
        $this->getAction(Enabler::ACTION)->disable('Payment Methods/Saved CC');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}